# INSECURE EXAMPLE - No network policies
# These pods have no network segmentation or traffic controls

apiVersion: v1
kind: Namespace
metadata:
  name: no-netpol-namespace
  labels:
    security: vulnerable

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-app
  namespace: no-netpol-namespace
  labels:
    app: frontend
    tier: web
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-app
  namespace: no-netpol-namespace
  labels:
    app: backend
    tier: api
spec:
  containers:
  - name: api
    image: python:3.9-slim
    command: ["/bin/sleep", "3600"]
    ports:
    - containerPort: 8000
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

# NOTE: No NetworkPolicy defined!
# All pods can communicate with each other and external networks without restriction
# This is a HIGH severity security issue